apiVersion: v1
kind: Service
metadata:
  name: shorten-service
  namespace: url-shortener
spec:
  selector:
    app: shorten-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081