version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SHORTEN_SERVICE_URL=http://shorten-service:8081
      - REDIRECT_SERVICE_URL=http://redirect-service:8082
    depends_on:
      - shorten-service
      - redirect-service
    networks:
      - url-shortener-network

  shorten-service:
    build: ./shorten-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=urlshortener
      - DB_PASSWORD=secretpassword
      - DB_NAME=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - url-shortener-network

  redirect-service:
    build: ./redirect-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=urlshortener
      - DB_PASSWORD=secretpassword
      - DB_NAME=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - url-shortener-network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - url-shortener-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - url-shortener-network

volumes:
  postgres-data:
  redis-data:

networks:
  url-shortener-network:
    driver: bridge