apiVersion: v1
kind: Service
metadata:
  name: redirect-service
  namespace: url-shortener
spec:
  selector:
    app: redirect-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082